language: go 

go:
    - 1.7.x
    - master
addons:
    apt:
        packages:
            - nodejs
            - cmake
before_install:
    - mkdir ./server/secrets
    - echo -e "package secrets\n\nconst SubSecret=\"aaa\"\nconst SECRET=\"aaaa\"\nconst DB_DIAL_URL=\"mongodb://localhost\"" > ./server/secrets/secret.go 
    - npm install -g npm3
    - npm cache clean -f 
    - npm -v

install: 
    - go get ./server
    - go get "github.com/stretchr/testify/assert"
    - cd ./web-client 
    - /home/travis/.nvm/v0.10.36/bin/npm3 install
    - cd ..
script: 
    - go test -v ./server/tests
    - cd ./web-client; npm run test; cd ..
