language: go
sudo: required

go:
    - 1.7.x
    - master
before_install:
    - mkdir ./server/secrets
    - echo -e "package secrets\n\nconst SubSecret=\"aaa\"\nconst SECRET=\"aaaa\"\nconst DB_DIAL_URL=\"mongodb://localhost\"" > ./server/secrets/secret.go 
    - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    - sudo apt-get install nodejs

install: 
    - go get ./server
    - go get "github.com/stretchr/testify/assert"
    - cd ./web-client; npm install; cd ..
script: 
    - go test -v ./server/tests
    - cd ./web-client; npm run test; cd ..
