language: go 
go: 
    - "1.10.x"
    - master
addons:
    apt:
        packages:
            - nodejs
            - cmake
before_install:
    - nvm install v6.10.3
    - nvm use v6.10.3 
    - npm cache clean -f 
install:
    - go get -u github.com/golang/dep/cmd/dep
script:
    - make
    - make test 

