version: '2'
services:
  server:
    build: .
    ports:
      - ${PORT}:8000
    environment: 
      - POSTGRES_PASSWORD
      - DBConnString
      - UseSSL
      - CertKey
      - PrivKey
      - SigningKey
    command: ["./wait-for-it.sh", "db:5432", "--", "./conduit"] 
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - $PWD/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

